# Generated by Django 3.2.5 on 2021-07-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=64, verbose_name='населенный пункт')),
                ('phone', models.CharField(blank=True, max_length=16, verbose_name='телефон')),
                ('email', models.CharField(blank=True, max_length=64, verbose_name='электронная почта')),
                ('address', models.CharField(blank=True, max_length=256, verbose_name='адрес')),
            ],
        ),
    ]
